package responsevalidator;

public class Demo {
	public static void main(String[] args) throws Exception {
		
		
		String response = "{\r\n"
				+ "    \"TransResponse\": {\r\n"
				+ "        \"POSID\": \"\",\r\n"
				+ "        \"APPID\": \"\",\r\n"
				+ "        \"BatchNumber\": \"034001\",\r\n"
				+ "        \"TransDetailsData\": {\r\n"
				+ "            \"TransDetailData\": [\r\n"
				+ "                {\r\n"
				+ "                    \"CardNumber\": \"XXXXXXXXXXXX4444\",\r\n"
				+ "                    \"CardIdentifier\": \"2000000000002616\",\r\n"
				+ "                    \"OrigAurusPayTicketNum\": \"\",\r\n"
				+ "                    \"ProcessorToken\": \"\",\r\n"
				+ "                    \"ProcessorMerchantId\": \"0100001459\",\r\n"
				+ "                    \"LanguageIndicator\": \"\",\r\n"
				+ "                    \"ProcessorReferenceNumber\": \"\",\r\n"
				+ "                    \"EBTCashBalance\": \"\",\r\n"
				+ "                    \"DonationAmount\": \"\",\r\n"
				+ "                    \"DCCDetails\": {\r\n"
				+ "                        \"DCCMarginRatePercent\": \"\",\r\n"
				+ "                        \"DCCAlphaCurrencyCode\": \"\",\r\n"
				+ "                        \"DCCExchangeRate\": \"\",\r\n"
				+ "                        \"DCCValidHours\": \"\",\r\n"
				+ "                        \"DCCCurrencyCode\": \"\",\r\n"
				+ "                        \"DCCMinorUnits\": \"\",\r\n"
				+ "                        \"DCCCommissionPercent\": \"\",\r\n"
				+ "                        \"DCCCurrencyName\": \"\",\r\n"
				+ "                        \"DCCExchRateSrcName\": \"\",\r\n"
				+ "                        \"DCCOffered\": \"\",\r\n"
				+ "                        \"DCCResponseCode\": \"\",\r\n"
				+ "                        \"DCCExchRateSrcTime\": \"\",\r\n"
				+ "                        \"DCCFgnAmount\": \"\"\r\n"
				+ "                    },\r\n"
				+ "                    \"CardExpiryDate\": \"1234\",\r\n"
				+ "                    \"ProcessorTokenRespCode\": \"\",\r\n"
				+ "                    \"TransactionTypeCode\": \"4\",\r\n"
				+ "                    \"CardEntryMode\": \"K\",\r\n"
				+ "                    \"CardIndicator\": \"\",\r\n"
				+ "                    \"InvoiceNumber\": \"21212123455\",\r\n"
				+ "                    \"SessionId\": \"\",\r\n"
				+ "                    \"EcomResponseCode\": \"100\",\r\n"
				+ "                    \"ProcessorTId\": \"00000002\",\r\n"
				+ "                    \"ReceiptToken\": \"5555550000084444\",\r\n"
				+ "                    \"TransactionToken\": \"30042503430197602094\",\r\n"
				+ "                    \"BatchNumber\": \"034001\",\r\n"
				+ "                    \"CheckClearingStatus\": \"\",\r\n"
				+ "                    \"StateIdentifier\": \"\",\r\n"
				+ "                    \"ProcessorTokenRespText\": \"\",\r\n"
				+ "                    \"ReferenceNumber\": \"akak5263116\",\r\n"
				+ "                    \"FraudScoreInfo\": {\r\n"
				+ "                        \"Email\": \"\",\r\n"
				+ "                        \"RequestId\": \"7385889969096241604601\",\r\n"
				+ "                        \"PostalCode\": \"\",\r\n"
				+ "                        \"ServiceIdentifier\": \"\",\r\n"
				+ "                        \"RulesTripped\": \"\",\r\n"
				+ "                        \"ReasonCode\": \"100\",\r\n"
				+ "                        \"Decision\": \"ACCEPT\",\r\n"
				+ "                        \"EcomToken\": \"AxjzbwSTkGPQUsVWUmf5ADUCT35CJcKjSBX0J1UMmkmVdHpJMHgmAAAA/AJM\",\r\n"
				+ "                        \"Score\": \"18\",\r\n"
				+ "                        \"Remarks\": \"\",\r\n"
				+ "                        \"RequestToken\": \"AxjzbwSTkGPQUsVWUmf5ADUCT35CJcKjSBX0J1UMmkmVdHpJMHgmAAAA/AJM\",\r\n"
				+ "                        \"ReqTypeIndicator\": \"\",\r\n"
				+ "                        \"PhoneNumber\": \"\",\r\n"
				+ "                        \"OrigDecision\": \"\",\r\n"
				+ "                        \"StreetAddr\": \"\",\r\n"
				+ "                        \"FirstAndLastName\": \"\",\r\n"
				+ "                        \"ProcessorDecision\": \"\"\r\n"
				+ "                    },\r\n"
				+ "                    \"CustomerId\": \"\",\r\n"
				+ "                    \"OrderId\": \"21212123455\",\r\n"
				+ "                    \"SignatureReceiptFlag\": \"\",\r\n"
				+ "                    \"ECOMMInfo\": {\r\n"
				+ "                        \"OneTimeToken\": \"\",\r\n"
				+ "                        \"StoreId\": \"00500\",\r\n"
				+ "                        \"MerchantIdentifier\": \"100000026452\",\r\n"
				+ "                        \"AVSResult\": \"S\",\r\n"
				+ "                        \"OneOrderToken\": \"30042503430197602094\",\r\n"
				+ "                        \"CVVResult\": \"\",\r\n"
				+ "                        \"TerminalId\": \"64283102\"\r\n"
				+ "                    },\r\n"
				+ "                    \"BenefitExpiryDate\": \"\",\r\n"
				+ "                    \"FraudIndicator\": \"\",\r\n"
				+ "                    \"BenefitBeginningDate\": \"\",\r\n"
				+ "                    \"PaypageUrl\": \"\",\r\n"
				+ "                    \"ProcessorResponseCode\": \"000\",\r\n"
				+ "                    \"FleetPromptsData\": {\r\n"
				+ "                        \"DriverIDNumber\": \"\",\r\n"
				+ "                        \"LicenseNumber\": \"\",\r\n"
				+ "                        \"VehicleIDNumber\": \"\",\r\n"
				+ "                        \"CustomerData\": \"\",\r\n"
				+ "                        \"UserID\": \"\",\r\n"
				+ "                        \"DeptNumber\": \"\",\r\n"
				+ "                        \"PurchaseRestrictionsCode\": \"\",\r\n"
				+ "                        \"Odometer\": \"\",\r\n"
				+ "                        \"JobNumber\": \"\",\r\n"
				+ "                        \"EmployeeIDNumber\": \"\",\r\n"
				+ "                        \"VehicleNumber\": \"\",\r\n"
				+ "                        \"JobID\": \"\"\r\n"
				+ "                    },\r\n"
				+ "                    \"SessionValidity\": \"\",\r\n"
				+ "                    \"EMVData\": \"\",\r\n"
				+ "                    \"AdditionalTags\": {\r\n"
				+ "                        \"Tags\": {\r\n"
				+ "                            \"Tag\": [\r\n"
				+ "                                {\r\n"
				+ "                                    \"Value\": {\r\n"
				+ "                                        \"DeclineIndicator\": \"\",\r\n"
				+ "                                        \"AuthCode\": \"\",\r\n"
				+ "                                        \"MsgCode\": \"\",\r\n"
				+ "                                        \"PromptField\": \"\",\r\n"
				+ "                                        \"WEBMsgCode\": \"\",\r\n"
				+ "                                        \"CvvCode\": \"\",\r\n"
				+ "                                        \"CreditAuthCode\": \"\",\r\n"
				+ "                                        \"ReasonCode\": \"\",\r\n"
				+ "                                        \"AvsCode\": \"\",\r\n"
				+ "                                        \"MaxAtt\": \"\",\r\n"
				+ "                                        \"CancelAmount\": \"\",\r\n"
				+ "                                        \"Desc\": \"\",\r\n"
				+ "                                        \"srv\": \"\",\r\n"
				+ "                                        \"CMOSMsgCode\": \"\",\r\n"
				+ "                                        \"CancelFlag\": \"\",\r\n"
				+ "                                        \"CancelCode\": \"\"\r\n"
				+ "                                    },\r\n"
				+ "                                    \"Key\": \"CustomMsgCodes\"\r\n"
				+ "                                },\r\n"
				+ "                                {\r\n"
				+ "                                    \"Value\": \"21212123455\",\r\n"
				+ "                                    \"Key\": \"InvoiceNumber\"\r\n"
				+ "                                },\r\n"
				+ "                                {\r\n"
				+ "                                    \"Value\": \"\",\r\n"
				+ "                                    \"Key\": \"ProcessorTransactionID\"\r\n"
				+ "                                },\r\n"
				+ "                                {\r\n"
				+ "                                    \"Value\": \"\",\r\n"
				+ "                                    \"Key\": \"ProcessorPayerId\"\r\n"
				+ "                                }\r\n"
				+ "                            ]\r\n"
				+ "                        }\r\n"
				+ "                    },\r\n"
				+ "                    \"ResponseText\": \"APPROVAL\",\r\n"
				+ "                    \"OrigResponseCode\": \"\",\r\n"
				+ "                    \"WalletIdentifier\": \"\",\r\n"
				+ "                    \"AurusProcessorId\": \"30\",\r\n"
				+ "                    \"CRMToken\": \"\",\r\n"
				+ "                    \"TotalApprovedAmount\": \"10.00\",\r\n"
				+ "                    \"ClerkID\": \"\",\r\n"
				+ "                    \"IssuerNumber\": \"\",\r\n"
				+ "                    \"EMVDataInTLVFormat\": \"\",\r\n"
				+ "                    \"TransactionType\": \"04\",\r\n"
				+ "                    \"EBTCashAvailableBalance\": \"\",\r\n"
				+ "                    \"EBTType\": \"\",\r\n"
				+ "                    \"ProcessorDataFields\": {\r\n"
				+ "                        \"DataField6\": \"\",\r\n"
				+ "                        \"DataField5\": \"\",\r\n"
				+ "                        \"DataField4\": \"\",\r\n"
				+ "                        \"DataField3\": \"\",\r\n"
				+ "                        \"DataField2\": \"\",\r\n"
				+ "                        \"DataField1\": \"0201MCC651117\"\r\n"
				+ "                    },\r\n"
				+ "                    \"DeviceId\": \"\",\r\n"
				+ "                    \"AuruspayTransactionId\": \"192250343019759575\",\r\n"
				+ "                    \"KSNBlock\": \"\",\r\n"
				+ "                    \"TransactionSequenceNumber\": \"566450\",\r\n"
				+ "                    \"BillingAddress\": {\r\n"
				+ "                        \"BillingCity\": \"\",\r\n"
				+ "                        \"BillingZip\": \"\",\r\n"
				+ "                        \"BillingProvince\": \"\",\r\n"
				+ "                        \"BillingAddressLine1\": \"\",\r\n"
				+ "                        \"BillingAddressLine2\": \"\",\r\n"
				+ "                        \"BillingAddressLine3\": \"\",\r\n"
				+ "                        \"BillingCountry\": \"\",\r\n"
				+ "                        \"BillingEmailId\": \"\",\r\n"
				+ "                        \"BillingMobileNumber\": \"\",\r\n"
				+ "                        \"BillingFirstName\": \"\",\r\n"
				+ "                        \"BillingLastName\": \"\",\r\n"
				+ "                        \"BillingOtherNumber\": \"\",\r\n"
				+ "                        \"BillingState\": \"\",\r\n"
				+ "                        \"BillingMiddleName\": \"\"\r\n"
				+ "                    },\r\n"
				+ "                    \"CashbackAmount\": \"\",\r\n"
				+ "                    \"TransactionIdentifier\": \"192250343019759575\",\r\n"
				+ "                    \"CardType\": \"MCC\",\r\n"
				+ "                    \"OrigTransactionIdentifier\": \"\",\r\n"
				+ "                    \"PartialApprovedFlag\": \"0\",\r\n"
				+ "                    \"SplitType\": \"\",\r\n"
				+ "                    \"AnnualPercentageRate\": \"\",\r\n"
				+ "                    \"SourceTransactionId\": \"akak5263116\",\r\n"
				+ "                    \"FallbackIndicator\": \"\",\r\n"
				+ "                    \"CustomerName\": \"john dae\",\r\n"
				+ "                    \"InterOperableToken\": \"\",\r\n"
				+ "                    \"TokenId\": \"\",\r\n"
				+ "                    \"PaymentItemCategory\": \"\",\r\n"
				+ "                    \"SplitPaymentNum\": \"\",\r\n"
				+ "                    \"TransactionDate\": \"02032025\",\r\n"
				+ "                    \"CardClass\": \"\",\r\n"
				+ "                    \"ResponseCode\": \"00000\",\r\n"
				+ "                    \"BalanceAmount\": \"0.00\",\r\n"
				+ "                    \"ReferralNUM\": \"555555XXXXXX4444\",\r\n"
				+ "                    \"AnnualPercentageRateType\": \"\",\r\n"
				+ "                    \"EMVDetailsData\": \"\",\r\n"
				+ "                    \"Level3Capable\": \"\",\r\n"
				+ "                    \"GiftCardTypePassCode\": \"\",\r\n"
				+ "                    \"PINBlock\": \"\",\r\n"
				+ "                    \"SubCardType\": \"\",\r\n"
				+ "                    \"ApprovalCode\": \"610080\",\r\n"
				+ "                    \"EBTFoodAvailableBalance\": \"\",\r\n"
				+ "                    \"TransactionAmount\": \"10.00\",\r\n"
				+ "                    \"TransactionTime\": \"082317\",\r\n"
				+ "                    \"OrigResponseText\": \"\",\r\n"
				+ "                    \"EcomResponseText\": \"ACCEPT\",\r\n"
				+ "                    \"AuthAVSResult\": \"S\",\r\n"
				+ "                    \"TravelInfo\": {\r\n"
				+ "                        \"PNRNumber\": \"\"\r\n"
				+ "                    },\r\n"
				+ "                    \"ProcessorResponseText\": \"APPROVAL\",\r\n"
				+ "                    \"AuthCVVResult\": \"\",\r\n"
				+ "                    \"RequestedTipAmount\": \"0.00\"\r\n"
				+ "                }\r\n"
				+ "            ]\r\n"
				+ "        },\r\n"
				+ "        \"AdditionalTags\": {\r\n"
				+ "            \"Tags\": {\r\n"
				+ "                \"Tag\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"Value\": {\r\n"
				+ "                            \"DeclineIndicator\": \"\",\r\n"
				+ "                            \"AuthCode\": \"\",\r\n"
				+ "                            \"MsgCode\": \"\",\r\n"
				+ "                            \"PromptField\": \"\",\r\n"
				+ "                            \"WEBMsgCode\": \"\",\r\n"
				+ "                            \"CvvCode\": \"\",\r\n"
				+ "                            \"CreditAuthCode\": \"\",\r\n"
				+ "                            \"ReasonCode\": \"\",\r\n"
				+ "                            \"AvsCode\": \"\",\r\n"
				+ "                            \"MaxAtt\": \"\",\r\n"
				+ "                            \"CancelAmount\": \"\",\r\n"
				+ "                            \"Desc\": \"\",\r\n"
				+ "                            \"srv\": \"\",\r\n"
				+ "                            \"CMOSMsgCode\": \"\",\r\n"
				+ "                            \"CancelFlag\": \"\",\r\n"
				+ "                            \"CancelCode\": \"\"\r\n"
				+ "                        },\r\n"
				+ "                        \"Key\": \"CustomMsgCodes\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"Value\": \"21212123455\",\r\n"
				+ "                        \"Key\": \"InvoiceNumber\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"Value\": \"\",\r\n"
				+ "                        \"Key\": \"ProcessorTransactionID\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"Value\": \"\",\r\n"
				+ "                        \"Key\": \"ProcessorPayerId\"\r\n"
				+ "                    }\r\n"
				+ "                ]\r\n"
				+ "            }\r\n"
				+ "        },\r\n"
				+ "        \"SessionId\": \"\",\r\n"
				+ "        \"AurusPayTicketNum\": \"225034301975956000\"\r\n"
				+ "    }\r\n"
				+ "}";
		
		JSON_ res = new JSON_(response);
		System.out.println(res.getParameterValue("CardNumber"));
	}
	
	
	

}
