package utilities;

import org.testng.annotations.Test;

import responsevalidator.Response_Parameters;

public class Demo {
	
	String[] parameters = { "CardToken", "CardIdentifier", "CRMToken", "CardEntryMode", "TransactionTypeCode",
			"TransactionSequenceNumber", "CardType", "SubCardType", "TotalApprovedAmount", "ResponseText",
			"ResponseCode", "TransactionIdentifier", "AurusPayTicketNum", "ApprovalCode", "ProcessorMerchantId" };
	@Test
	public void test() throws Exception {
	
		Response_Parameters rs = new Response_Parameters(res);
	String ci = 	rs.getParameterValue("CardIdentifier");
	System.out.println(ci);
		rs.print_Response("SAle", parameters);
		
		Response_Parameters r = new Response_Parameters(Rs);
		String c = 	r.getParameterValue("CardIdentifier");
		System.out.println(c);
		r.print_Response("SAle", parameters);
		
		
	}

	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	String res = "\r\n"
			+ "<TransResponse>\r\n"
			+ "  <CCTID>01</CCTID>\r\n"
			+ "  <POSID>S00784R0100</POSID>\r\n"
			+ "  <APPID>01</APPID>\r\n"
			+ "  <TransDetailsData>\r\n"
			+ "    <TransDetailData>\r\n"
			+ "      <CardNumber>400000XXXXXX0028</CardNumber>\r\n"
			+ "      <TotalApprovedAmount>514.27</TotalApprovedAmount>\r\n"
			+ "      <EMVDataInTLVFormat>AID%7EA0000006200620%1ETVR%7E8000048000%1EIAD%7E0106A00003800000%1ETSI%7E6800%1EARC%7E3030</EMVDataInTLVFormat>\r\n"
			+ "      <EBTType />\r\n"
			+ "      <CardIdentifier>2000000000002799</CardIdentifier>\r\n"
			+ "      <ProcessorToken>400000XXXXXX0028</ProcessorToken>\r\n"
			+ "      <ProcessorMerchantId>577000322896</ProcessorMerchantId>\r\n"
			+ "      <TransactionSequenceNumber>000005</TransactionSequenceNumber>\r\n"
			+ "      <CardToken>400000XXXXXX0028</CardToken>\r\n"
			+ "      <LanguageIndicator>00</LanguageIndicator>\r\n"
			+ "      <DCCDetails>\r\n"
			+ "        <DCCMinorUnits />\r\n"
			+ "        <DCCMarginRatePercent />\r\n"
			+ "        <DCCAlphaCurrencyCode />\r\n"
			+ "        <DCCExchRateSrcName />\r\n"
			+ "        <DCCOffered>0</DCCOffered>\r\n"
			+ "        <DCCResponseCode />\r\n"
			+ "        <DCCValidHours />\r\n"
			+ "        <DCCExchRateSrcTime />\r\n"
			+ "        <DCCCurrencyCode />\r\n"
			+ "      </DCCDetails>\r\n"
			+ "      <CardType>VID</CardType>\r\n"
			+ "      <TransactionIdentifier>193240022212455801</TransactionIdentifier>\r\n"
			+ "      <CardExpiryDate>1225</CardExpiryDate>\r\n"
			+ "      <PartialApprovedFlag>N</PartialApprovedFlag>\r\n"
			+ "      <TransactionTypeCode>21</TransactionTypeCode>\r\n"
			+ "      <ReceiptDetails>\r\n"
			+ "        <ReceiptData>\r\n"
			+ "          <LanguageIndicator>00</LanguageIndicator>\r\n"
			+ "          <ReceiptInfo>\r\n"
			+ "            <Line>AMOUNT:514.27</Line>\r\n"
			+ "            <Line>CARD:VISA DEBIT XXXX0028 EMV</Line>\r\n"
			+ "            <Line>APPROVAL CODE:097292</Line>\r\n"
			+ "            <Line>AID:A0000006200620</Line>\r\n"
			+ "            <Line>TVR:8000048000</Line>\r\n"
			+ "            <Line>IAD:0106A00003800000</Line>\r\n"
			+ "            <Line>TSI:6800</Line>\r\n"
			+ "            <Line>ARC:00</Line>\r\n"
			+ "            <Line>APPLICATION CRYPTOGRAM:C356A442F687C154</Line>\r\n"
			+ "            <Line>APPLICATION PREFERRED NAME:Debit</Line>\r\n"
			+ "            <Line>APPLICATION LABEL:DNA</Line>\r\n"
			+ "            <Line>CVM:Verified By PIN</Line>\r\n"
			+ "          </ReceiptInfo>\r\n"
			+ "        </ReceiptData>\r\n"
			+ "      </ReceiptDetails>\r\n"
			+ "      <FallbackIndicator>0</FallbackIndicator>\r\n"
			+ "      <CardEntryMode>I</CardEntryMode>\r\n"
			+ "      <TipAmount>0.00</TipAmount>\r\n"
			+ "      <CustomerName>TEST CARD 18       UAT USA</CustomerName>\r\n"
			+ "      <TransactionDate>01022024</TransactionDate>\r\n"
			+ "      <AdditionalReceiptInfo>\r\n"
			+ "        <Line>AMOUNT:514.27</Line>\r\n"
			+ "        <Line>CARD:VISA DEBIT XXXX0028 EMV</Line>\r\n"
			+ "        <Line>APPROVAL CODE:097292</Line>\r\n"
			+ "        <Line>AID:A0000006200620</Line>\r\n"
			+ "        <Line>TVR:8000048000</Line>\r\n"
			+ "        <Line>IAD:0106A00003800000</Line>\r\n"
			+ "        <Line>TSI:6800</Line>\r\n"
			+ "        <Line>ARC:00</Line>\r\n"
			+ "        <Line>APPLICATION CRYPTOGRAM:C356A442F687C154</Line>\r\n"
			+ "        <Line>APPLICATION PREFERRED NAME:Debit</Line>\r\n"
			+ "        <Line>APPLICATION LABEL:DNA</Line>\r\n"
			+ "        <Line>CVM:Verified By PIN</Line>\r\n"
			+ "      </AdditionalReceiptInfo>\r\n"
			+ "      <CashBackAmount>0.00</CashBackAmount>\r\n"
			+ "      <AddressVerification />\r\n"
			+ "      <ResponseCode>00000</ResponseCode>\r\n"
			+ "      <ReceiptToken>4000001111120028</ReceiptToken>\r\n"
			+ "      <BalanceAmount>0.00</BalanceAmount>\r\n"
			+ "      <ReferenceNumber>093000164374</ReferenceNumber>\r\n"
			+ "      <GiftCardTypePassCode />\r\n"
			+ "      <LangIndicator>00</LangIndicator>\r\n"
			+ "      <EMVFlag>1</EMVFlag>\r\n"
			+ "      <SignatureReceiptFlag>2</SignatureReceiptFlag>\r\n"
			+ "      <ECOMMInfo>\r\n"
			+ "        <OneOrderToken />\r\n"
			+ "      </ECOMMInfo>\r\n"
			+ "      <ApprovalCode>097292</ApprovalCode>\r\n"
			+ "      <TransactionAmount>514.27</TransactionAmount>\r\n"
			+ "      <EPPDetailsInfo>\r\n"
			+ "        <STAN>00472559</STAN>\r\n"
			+ "      </EPPDetailsInfo>\r\n"
			+ "      <TransactionTime>060844</TransactionTime>\r\n"
			+ "      <LoyaltyInfo />\r\n"
			+ "      <ProcessorResponseCode>00</ProcessorResponseCode>\r\n"
			+ "      <EMVData>[FS]MerchantID~577000322896[FS]TerminalID~[FS]ARC~00[FS]ISO~00[FS]AID~A0000006200620[FS]TVR~8000048000[FS]TSI~6800[FS]IAD~0106A00003800000[FS]App Pref Name~Debit[FS]App Label~DNA[FS]RespDate~01022024[FS]RespTime~060844</EMVData>\r\n"
			+ "      <VoidData />\r\n"
			+ "      <AuthorizedAmount>514.27</AuthorizedAmount>\r\n"
			+ "      <ResponseText>APPROVAL</ResponseText>\r\n"
			+ "      <CRMToken>8910000010000048618</CRMToken>\r\n"
			+ "    </TransDetailData>\r\n"
			+ "  </TransDetailsData>\r\n"
			+ "  <BatchNumber>002001</BatchNumber>\r\n"
			+ "  <AurusPayTicketNum>324002221245587631</AurusPayTicketNum>\r\n"
			+ "</TransResponse>";
	
	String Rs = "\r\n"
			+ "<TransResponse>\r\n"
			+ "  <CCTID>01</CCTID>\r\n"
			+ "  <POSID>S00784R0100</POSID>\r\n"
			+ "  <APPID>01</APPID>\r\n"
			+ "  <TransDetailsData>\r\n"
			+ "    <TransDetailData>\r\n"
			+ "      <CardNumber>400000XXXXXX0028</CardNumber>\r\n"
			+ "      <TotalApprovedAmount>514.27</TotalApprovedAmount>\r\n"
			+ "      <EMVDataInTLVFormat>AID%7EA0000006200620%1ETVR%7E8000048000%1EIAD%7E0106A00003800000%1ETSI%7E6800%1EARC%7E3030</EMVDataInTLVFormat>\r\n"
			+ "      <EBTType />\r\n"
			+ "      <CardIdentifier>2AAAAAAAAAAAAAAAAAAAAAAAAAA2799</CardIdentifier>\r\n"
			+ "      <ProcessorToken>400000XXXXXX0028</ProcessorToken>\r\n"
			+ "      <ProcessorMerchantId>577000322896</ProcessorMerchantId>\r\n"
			+ "      <TransactionSequenceNumber>000005</TransactionSequenceNumber>\r\n"
			+ "      <CardToken>400000XXXXXX0028</CardToken>\r\n"
			+ "      <LanguageIndicator>00</LanguageIndicator>\r\n"
			+ "      <DCCDetails>\r\n"
			+ "        <DCCMinorUnits />\r\n"
			+ "        <DCCMarginRatePercent />\r\n"
			+ "        <DCCAlphaCurrencyCode />\r\n"
			+ "        <DCCExchRateSrcName />\r\n"
			+ "        <DCCOffered>0</DCCOffered>\r\n"
			+ "        <DCCResponseCode />\r\n"
			+ "        <DCCValidHours />\r\n"
			+ "        <DCCExchRateSrcTime />\r\n"
			+ "        <DCCCurrencyCode />\r\n"
			+ "      </DCCDetails>\r\n"
			+ "      <CardType>VID</CardType>\r\n"
			+ "      <TransactionIdentifier>193240022212455801</TransactionIdentifier>\r\n"
			+ "      <CardExpiryDate>1225</CardExpiryDate>\r\n"
			+ "      <PartialApprovedFlag>N</PartialApprovedFlag>\r\n"
			+ "      <TransactionTypeCode>21</TransactionTypeCode>\r\n"
			+ "      <ReceiptDetails>\r\n"
			+ "        <ReceiptData>\r\n"
			+ "          <LanguageIndicator>00</LanguageIndicator>\r\n"
			+ "          <ReceiptInfo>\r\n"
			+ "            <Line>AMOUNT:514.27</Line>\r\n"
			+ "            <Line>CARD:VISA DEBIT XXXX0028 EMV</Line>\r\n"
			+ "            <Line>APPROVAL CODE:097292</Line>\r\n"
			+ "            <Line>AID:A0000006200620</Line>\r\n"
			+ "            <Line>TVR:8000048000</Line>\r\n"
			+ "            <Line>IAD:0106A00003800000</Line>\r\n"
			+ "            <Line>TSI:6800</Line>\r\n"
			+ "            <Line>ARC:00</Line>\r\n"
			+ "            <Line>APPLICATION CRYPTOGRAM:C356A442F687C154</Line>\r\n"
			+ "            <Line>APPLICATION PREFERRED NAME:Debit</Line>\r\n"
			+ "            <Line>APPLICATION LABEL:DNA</Line>\r\n"
			+ "            <Line>CVM:Verified By PIN</Line>\r\n"
			+ "          </ReceiptInfo>\r\n"
			+ "        </ReceiptData>\r\n"
			+ "      </ReceiptDetails>\r\n"
			+ "      <FallbackIndicator>0</FallbackIndicator>\r\n"
			+ "      <CardEntryMode>I</CardEntryMode>\r\n"
			+ "      <TipAmount>0.00</TipAmount>\r\n"
			+ "      <CustomerName>TEST CARD 18       UAT USA</CustomerName>\r\n"
			+ "      <TransactionDate>01022024</TransactionDate>\r\n"
			+ "      <AdditionalReceiptInfo>\r\n"
			+ "        <Line>AMOUNT:514.27</Line>\r\n"
			+ "        <Line>CARD:VISA DEBIT XXXX0028 EMV</Line>\r\n"
			+ "        <Line>APPROVAL CODE:097292</Line>\r\n"
			+ "        <Line>AID:A0000006200620</Line>\r\n"
			+ "        <Line>TVR:8000048000</Line>\r\n"
			+ "        <Line>IAD:0106A00003800000</Line>\r\n"
			+ "        <Line>TSI:6800</Line>\r\n"
			+ "        <Line>ARC:00</Line>\r\n"
			+ "        <Line>APPLICATION CRYPTOGRAM:C356A442F687C154</Line>\r\n"
			+ "        <Line>APPLICATION PREFERRED NAME:Debit</Line>\r\n"
			+ "        <Line>APPLICATION LABEL:DNA</Line>\r\n"
			+ "        <Line>CVM:Verified By PIN</Line>\r\n"
			+ "      </AdditionalReceiptInfo>\r\n"
			+ "      <CashBackAmount>0.00</CashBackAmount>\r\n"
			+ "      <AddressVerification />\r\n"
			+ "      <ResponseCode>00000</ResponseCode>\r\n"
			+ "      <ReceiptToken>4000001111120028</ReceiptToken>\r\n"
			+ "      <BalanceAmount>0.00</BalanceAmount>\r\n"
			+ "      <ReferenceNumber>093000164374</ReferenceNumber>\r\n"
			+ "      <GiftCardTypePassCode />\r\n"
			+ "      <LangIndicator>00</LangIndicator>\r\n"
			+ "      <EMVFlag>1</EMVFlag>\r\n"
			+ "      <SignatureReceiptFlag>2</SignatureReceiptFlag>\r\n"
			+ "      <ECOMMInfo>\r\n"
			+ "        <OneOrderToken />\r\n"
			+ "      </ECOMMInfo>\r\n"
			+ "      <ApprovalCode>097292</ApprovalCode>\r\n"
			+ "      <TransactionAmount>514.27</TransactionAmount>\r\n"
			+ "      <EPPDetailsInfo>\r\n"
			+ "        <STAN>00472559</STAN>\r\n"
			+ "      </EPPDetailsInfo>\r\n"
			+ "      <TransactionTime>060844</TransactionTime>\r\n"
			+ "      <LoyaltyInfo />\r\n"
			+ "      <ProcessorResponseCode>00</ProcessorResponseCode>\r\n"
			+ "      <EMVData>[FS]MerchantID~577000322896[FS]TerminalID~[FS]ARC~00[FS]ISO~00[FS]AID~A0000006200620[FS]TVR~8000048000[FS]TSI~6800[FS]IAD~0106A00003800000[FS]App Pref Name~Debit[FS]App Label~DNA[FS]RespDate~01022024[FS]RespTime~060844</EMVData>\r\n"
			+ "      <VoidData />\r\n"
			+ "      <AuthorizedAmount>514.27</AuthorizedAmount>\r\n"
			+ "      <ResponseText>APPROVAL</ResponseText>\r\n"
			+ "      <CRMToken>8910000010000048618</CRMToken>\r\n"
			+ "    </TransDetailData>\r\n"
			+ "  </TransDetailsData>\r\n"
			+ "  <BatchNumber>002001</BatchNumber>\r\n"
			+ "  <AurusPayTicketNum>324002221245587631</AurusPayTicketNum>\r\n"
			+ "</TransResponse>";
}
